import { Button, Palette } from "std-widgets.slint";
import { IconDisplay, IconSet } from "@lucide";
import { Actions } from "../../../../../actions.slint";
import { Fonts, IconSize, Space } from "../../../../../theme.slint";

export component FileMessage inherits HorizontalLayout {
    in property <string> body;
    in property <string> event-id;

    spacing: Space.md;
    alignment: start;

    IconDisplay {
        icon: IconSet.Paperclip;
        size: IconSize.sm;
        stroke: Palette.foreground;
    }

    Text {
        text: root.body;
        font-size: Fonts.body;
        vertical-alignment: center;
    }

    Button {
        text: @tr("Save");
        enabled: root.event-id != "";
        clicked => {
            Actions.save-file({ event-id: root.event-id, filename: root.body });
        }
    }
}
