import { Button, Palette } from "std-widgets.slint";
import { IconDisplay, IconSet } from "@lucide";
import { SaveFileRequest } from "../../types.slint";

export component FileMessage inherits HorizontalLayout {
    in property <string> body;
    in property <string> event-id;

    callback save-file(SaveFileRequest);

    spacing: 8px;
    alignment: start;

    IconDisplay {
        icon: IconSet.Paperclip;
        size: 16px;
        stroke: Palette.foreground.transparentize(0.2);
    }

    Text {
        text: root.body;
        font-size: 14px;
        vertical-alignment: center;
    }

    Button {
        text: @tr("Save");
        enabled: root.event-id != "";
        clicked => {
            root.save-file({ event-id: root.event-id, filename: root.body });
        }
    }
}
