import { Palette } from "std-widgets.slint";
import { IconDisplay, IconSet } from "@lucide";
import { AppStyle, Fonts, IconSize, Radius, Space } from "../../../../../theme.slint";

export component UtdMessage inherits Rectangle {
    height: layout.preferred-height;
    border-radius: Radius.xs;
    background: AppStyle.overlay-hover;

    layout := HorizontalLayout {
        padding: Space.md;
        padding-left: Space.md;
        padding-right: Space.md;
        spacing: Space.md;
        alignment: start;

        IconDisplay {
            icon: IconSet.LockKeyhole;
            size: IconSize.sm;
            stroke: AppStyle.foreground-muted;
        }

        Text {
            text: @tr("Unable to decrypt message");
            font-size: Fonts.label;
            font-italic: true;
            color: AppStyle.foreground-muted;
            vertical-alignment: center;
        }
    }
}
