import { Palette } from "std-widgets.slint";
import { IconDisplay, IconSet } from "@lucide";

export component UtdMessage inherits Rectangle {
    height: layout.preferred-height;
    border-radius: 4px;
    background: Palette.foreground.transparentize(0.92);

    layout := HorizontalLayout {
        padding: 6px;
        padding-left: 8px;
        padding-right: 8px;
        spacing: 6px;
        alignment: start;

        IconDisplay {
            icon: IconSet.LockKeyhole;
            size: 15px;
            stroke: Palette.foreground.transparentize(0.4);
        }

        Text {
            text: @tr("Unable to decrypt message");
            font-size: 13px;
            font-italic: true;
            color: Palette.foreground.transparentize(0.4);
            vertical-alignment: center;
        }
    }
}
