import { Palette } from "std-widgets.slint";

export component LoadingScreen inherits VerticalLayout {
    alignment: center;
    padding: 24px;
    spacing: 16px;

    in property <string> loading-status: "";
    in property <string> loading-error: "";

    Text {
        text: "U2DM";
        font-size: 32px;
        horizontal-alignment: center;
    }

    if root.loading-status != "": Text {
        text: root.loading-status;
        font-size: 13px;
        horizontal-alignment: center;
        color: Palette.foreground.transparentize(0.3);
    }

    if root.loading-error != "": Text {
        text: root.loading-error;
        color: red;
        font-size: 13px;
        horizontal-alignment: center;
    }
}
