export struct RoomEntry {
    id: string,
    name: string,
    unread: int,
    mentions: int,
    last-message-sender: string,
    last-message-kind: string,
    last-message-body: string,
    last-message-is-own: bool,
    last-message-time: string,
}

export struct SpaceEntry {
    id: string,
    name: string,
    unread: int,
    mentions: int,
    initial: string,
    avatar: image,
    has-avatar: bool,
}

export struct MessageEntry {
    unique-id: string,
    sender: string,
    body: string,
    timestamp: string,
    message-type: string,
    has-thumbnail: bool,
    thumbnail: image,
    image-width: int,
    image-height: int,
    event-id: string,
    has-avatar: bool,
    avatar: image,
    sender-initial: string,
    is-own: bool,
    has-reply: bool,
    reply-sender: string,
    reply-body: string,
}

export struct EmojiEntry {
    base: string,
    tones: [string],
    name: string,
}

export struct EmojiGroup {
    items: [EmojiEntry],
}

export struct EmojiInsert {
    text: string,
    caret: int,
}

export struct SendMessageRequest {
    room-id: string,
    body: string,
    reply-to: string,
}

export struct SaveFileRequest {
    event-id: string,
    filename: string,
}
