export struct RoomEntry {
    id: string,
    name: string,
    unread: int,
    mentions: int,
}

export struct MessageEntry {
    sender: string,
    body: string,
    timestamp: string,
    message-type: string,
    has-thumbnail: bool,
    thumbnail: image,
    image-width: int,
    image-height: int,
    event-id: string,
    has-avatar: bool,
    avatar: image,
    sender-initial: string,
    is-own: bool,
}

export struct SendMessageRequest {
    room-id: string,
    body: string,
}

export struct SaveFileRequest {
    event-id: string,
    filename: string,
}
