export struct RoomEntry {
    id: string,
    name: string,
    unread: int,
}

export struct MessageEntry {
    sender: string,
    body: string,
    timestamp: string,
    message-type: string,
    has-thumbnail: bool,
    thumbnail: image,
    event-id: string,
    has-avatar: bool,
    avatar: image,
}

export struct SendMessageRequest {
    room-id: string,
    body: string,
}

export struct SaveFileRequest {
    event-id: string,
    filename: string,
}
