import "fonts/Twemoji.ttf";

import {
    LoginPhase,
    ConnectionState,
    TimelineState,
    VerificationPhase,
    MediaState,
    MessageKind,
    PreviewKind,
    ServiceKind,
    LoginMethodKind,
} from "enums.slint";
import {
    LoginView,
    SessionView,
    DirectoryView,
    RoomView,
    StickerView,
    VerificationView,
} from "views.slint";
import { Actions } from "actions.slint";
import {
    EmojiStore,
} from "screens/chat/components/timeline/emoji-picker.slint";
export { EmojiStore }
export { LoginPhase, ConnectionState, TimelineState, VerificationPhase, MediaState }
export { MessageKind, PreviewKind, ServiceKind, LoginMethodKind }
export { LoginView, SessionView, DirectoryView, RoomView, StickerView, VerificationView }
export { Actions }
import { LoadingScreen } from "screens/login/loading.slint";
import { HomeserverScreen } from "screens/login/homeserver.slint";
import { CredentialsScreen } from "screens/login/credentials.slint";
import { ChatScreen } from "screens/chat/chat.slint";
import { VerificationDialog } from "components/verification.slint";

export component AppWindow inherits Window {
    title: @tr("U2DM Matrix Client");
    preferred-width: root.width;
    preferred-height: root.height;

    in-out property <string> input-homeserver: "matrix.org";
    in-out property <string> input-username: "";
    in-out property <string> input-password: "";
    in-out property <string> input-message: "";

    if LoginView.step == LoginPhase.loading: LoadingScreen { }

    if LoginView.step == LoginPhase.homeserver: HomeserverScreen {
        input-homeserver <=> root.input-homeserver;
    }

    if LoginView.step == LoginPhase.credentials: CredentialsScreen {
        input-username <=> root.input-username;
        input-password <=> root.input-password;
    }

    if LoginView.step == LoginPhase.logged-in: ChatScreen {
        input-message <=> root.input-message;
    }

    if VerificationView.visible && LoginView.step == LoginPhase.logged-in: VerificationDialog { }
}
